#pragma once

#define ERROR_ARGUMENT_COUNT 1
#define ERROR_SYNTAX_ERROR 2
#define ERROR_INVALID_FORMAT 3
#define ERROR_UNABLE_TO_OPEN_FILE 4
#define ERROR_INVALID_ARGUMENT 5
#define ERROR_INVALID_OPTION 6
#define ERROR_CACHE_ERROR 7
#define ERROR_DATA_ERROR 8

#define TYPE_UNDEF 0
#define TYPE_INDENT 1
#define TYPE_CONST 2
#define TYPE_STRING 3
#define TYPE_SYMBOL 4
#define TYPE_OPERATOR 5
