#define ERROR_ARGUMENT_COUNT 1
#define ERROR_SYNTAX_ERROR 2

#define TYPE_UNDEF 0
#define TYPE_KEYWORD 1
#define TYPE_INDENT 2
#define TYPE_CONST 3
#define TYPE_STRING 4
#define TYPE_SYMBOL 5
#define TYPE_OPERATOR 6
#define TYPE_NEWLINE 7

#define VARIABLE_INT 0
